apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - name: pokedex-container
          image: samuelfdev/pokedex:1.0